import os
import yaml
import sys
import subprocess

import hydra
from omegaconf import OmegaConf, DictConfig

from jinja2 import Environment, FileSystemLoader

from dataclasses import dataclass

@hydra.main(config_path="hydra_config", config_name="base", version_base=None)
def main(cfg: DictConfig):
    # ----------------------------------------------------------------------- #
    #  Share values
    # ----------------------------------------------------------------------- #
    job = cfg.job

    # -- Job
    cfg.path.file_yaml_job   = f"{job}.yaml"
    cfg.path.file_sbatch_job = f"{job}.sbatch"
    cfg.sbatch_config.job    = cfg.job

    # -- Yaml
    os.makedirs(cfg.path.dir_yaml_jobs, exist_ok = True)
    path_yaml = os.path.join(cfg.path.dir_yaml_jobs, cfg.path.file_yaml_job)
    cfg.sbatch_config.yaml_config = path_yaml

    # ----------------------------------------------------------------------- #
    #  YAML
    # ----------------------------------------------------------------------- #
    print("Generated YAML Script:")
    print(OmegaConf.to_yaml(cfg.exp_mfu))
    print()

    path_yaml_job = os.path.join(cfg.path.dir_yaml_jobs, cfg.path.file_yaml_job)
    with open(path_yaml_job, 'w') as fh:
        fh.write(OmegaConf.to_yaml(cfg.exp_mfu))

        fh.write("\n")
        end_note = '# THIS SCRIPT IS GENERATED BY EXECUTING: \n# python ' + ' '.join(sys.argv)
        fh.write(end_note)


    # ----------------------------------------------------------------------- #
    #  SBATCH
    # ----------------------------------------------------------------------- #
    env             = Environment(loader=FileSystemLoader(cfg.path.dir_sbatch_template))
    template        = env.get_template(cfg.path.file_sbatch_template)
    rendered_script = template.render(**cfg.sbatch_config)

    print("Generated SBATCH Script:")
    print(rendered_script)
    print()

    os.makedirs(cfg.path.dir_sbatch_jobs, exist_ok = True)
    path_sbatch_job = os.path.join(cfg.path.dir_sbatch_jobs, cfg.path.file_sbatch_job)
    with open(path_sbatch_job, 'w') as fh:
        fh.write(rendered_script)

        fh.write("\n")
        end_note = '# THIS SCRIPT IS GENERATED BY EXECUTING: \n# python ' + ' '.join(sys.argv)
        fh.write(end_note)

    if cfg.auto_submit:
        # Executing the sbatch script
        sbatch_command = f"sbatch {path_sbatch_job}"
        print(sbatch_command)
        os.system(sbatch_command)

    # ----------------------------------------------------------------------- #
    #  PREEMPTIVE CHECKPOINT METADATA
    # ----------------------------------------------------------------------- #
    # Remove preempt checkpoint metadata if user chooses to specify their own
    dir_preempt  = 'preempt'
    file_preempt = f'{cfg.job}.dat'
    path_preempt = os.path.join(dir_preempt, file_preempt)
    if cfg.skip_preempt:
        try:
            os.remove(path_preempt)
            print(f"Preemptive checkpoint ignored.  Removed existing checkpoint file: '{path_preempt}'")
        except Exception as e:
            print(f"An error occurred while trying to remove the file: {e}.  It might have been removed already.")
    if os.path.exists(path_preempt):
        if cfg.exp_mfu.checkpoint.path_chkpt_prev is not None:
            try:
                os.remove(path_preempt)
                print(f"User specified path_chkpt_prev is not None.  File '{path_preempt}' has been removed successfully.")
            except Exception as e:
                print(f"An error occurred while trying to remove the file: {e}")


if __name__ == "__main__":
    main()
